RouteDelivery.MVC/Controllers/DeliveryScheduleController.cs
using RouteDelivery.Data;
using RouteDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RouteDelivery.Controllers
{
    public class DriverScheduleController : Controller
    {
        private IUnitOfWork _uof;

        public DriverScheduleController(IUnitOfWork uof)
        {
            _uof = uof;
        }

        public ActionResult Index(int Id)
        {
            var DriverSchedules = _uof.DeliverySchedule.Find(d => d.OptimizationRequestID == Id);

            if (DriverSchedules != null)
            {
                return View(DriverSchedules);
            }
            else
            {
                return RedirectToAction("Index", "OptimizationRequestController");
            }

        }

        [HttpGet]
        public ActionResult Create()
        {
            var DriverSchedule = new DeliverySchedule();

            return View(DriverSchedule);
        }

        [HttpPost]
        public ActionResult Create(DeliverySchedule newDriverSchedules)
        {
            if (ModelState.IsValid)
            {
                _uof.DeliverySchedule.Add(newDriverSchedules);
                _uof.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(newDriverSchedules);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var DriverScheduleEdit = _uof.DeliverySchedule.FindByID(Id);

            return View(DriverScheduleEdit);
        }

        [HttpPost]
        public ActionResult Edit(DeliverySchedule DriverScheduleEdit)
        {
            if (ModelState.IsValid)
            {
                _uof.DeliverySchedule.Update(DriverScheduleEdit);
                _uof.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(DriverScheduleEdit);
        }

        public ActionResult Delete(int Id)
        {
            var DriverScheduleDel = _uof.DeliverySchedule.FindByID(Id);

            if (DriverScheduleDel != null)
            {
                _uof.DeliverySchedule.Remove(DriverScheduleDel);
                _uof.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
}

RouteDelivery.MVC/Controllers/OptimizationRequestController.cs
using RouteDelivery.Data;
using RouteDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RouteDelivery.OptimizationEngine;
using RouteDelivery.Data.Implementations;
using Hangfire;

namespace RouteDelivery.Data
{
    public class OptimizationRequestController : Controller
    {
        private IUnitOfWork _uof;
        private IOptimizationEngine _optiEngine;

        public OptimizationRequestController()
        {
            _uof = new UnitOfWork();
            _optiEngine = new OptimizationEngine.OptimizationEngine(_uof);
        }

        public ActionResult Index()
        {
            var optimizationRequests = _uof.OptimizationRequests.FindAll();

            return View(optimizationRequests);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var optimizationRequest = new OptimizationRequest();

            return View(optimizationRequest);
        }

        [HttpPost]
        public ActionResult Create(OptimizationRequest newOptimizationRequest)
        {
            if (ModelState.IsValid)
            {
                _uof.OptimizationRequests.Add(newOptimizationRequest);
                _uof.SaveChanges();

                ProcessOptimizationRequest(newOptimizationRequest);

                return RedirectToAction("Index");
            }

            return View(newOptimizationRequest);
        }

        public void ProcessOptimizationRequest(OptimizationRequest newOptimizationRequest)
        {
            BackgroundJob.Enqueue(() => _optiEngine.OptimizeDeliveries(newOptimizationRequest.ID));
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var optimizationRequestEdit = _uof.OptimizationRequests.FindByID(Id);

            return View(optimizationRequestEdit);
        }

        [HttpPost]
        public ActionResult Edit(OptimizationRequest OptimizationRequestEdit)
        {
            if (ModelState.IsValid)
            {
                _uof.OptimizationRequests.Update(OptimizationRequestEdit);
                _uof.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(OptimizationRequestEdit);
        }

        public ActionResult Delete(int Id)
        {
            var OptimizationRequestDel = _uof.OptimizationRequests.FindByID(Id);

            if (OptimizationRequestDel != null)
            {
                _uof.OptimizationRequests.Remove(OptimizationRequestDel);
                _uof.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }

}

RouteDelivery.MVC/Views/OptimizationRequest/Create.cshtml
@model RouteDelivery.Models.OptimizationRequest

@{
    ViewBag.Title = "Create Schedule Optimization Request";
}

<h2>Create Schedule Optimization Request</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ScheduleDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScheduleDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ScheduleDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RouteDelivery.MVC/Views/OptimizationRequest/Edit.cshtml
@model RouteDelivery.Models.OptimizationRequest

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OptimizationRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ScheduleDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScheduleDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ScheduleDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RouteDelivery.MVC/Views/OptimizationRequest/Index.cshtml
@model IEnumerable<RouteDelivery.Models.OptimizationRequest>

@{
    ViewBag.Title = "Optimization Request";
}

<h2>Optimization Request</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RequestDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScheduleDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusText)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RequestDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScheduleDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusText)
        </td>
        <td>
            @Html.ActionLink("Driver Schedule", "Index", "DriverSchedule", new { Id=item.ID },null) 
        </td>
    </tr>
}

</table>