AzureADAuth/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;

namespace AzureADAuth.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {
        [Route("signin")]
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" });
        }

        [Route("signout")]
        [HttpPost]
        public async Task SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }
    }
}

AzureADAuth/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AzureADAuth.Models;
using AzureADAuth.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.WindowsAzure.Storage;

namespace AzureADAuth.Controllers
{
    [Route("[controller]/[action]")]
    public class ImageController : Controller
    {
        private readonly ImageStore imageStore;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public ImageController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            var currentContext = _httpContextAccessor.HttpContext;
            var accessToken = currentContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken).Result;
            this.imageStore = new ImageStore(accessToken);
            //this.imageStore = new ImageStore();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile image)
        {
            try
            {
                if (image != null)
                {
                    using (var stream = image.OpenReadStream())
                    {
                        var imageId = await imageStore.SaveImage(stream);
                        return RedirectToAction("Show", new { imageId });
                    }
                }
            }
            catch (StorageException ex)
            {
                //if(ex.RequestInformation.HttpStatusCode==(int)HttpStatusCode.Forbidden)

            }
            catch (Exception)
            {

                throw;
            }
           
            return View();
        }

        [HttpGet("{imageId}")]
        public ActionResult Show(string imageId)
        {
            var model = new ShowModel { Uri = imageStore.UriFor(imageId) };
            return View(model);
        }
    }
}

AzureADAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation"><a asp-controller="Home" asp-action="DeviceCode">Device Code Flow</a></li>
                    <li role="presentation"><a href="/ServerToServerCommunication">TokenForServerToServerCommunication</a></li>
                    <li role="presentation"><a href="/Authorization/Index">Authorization code flow</a></li>
                    <li role="presentation"><a asp-controller="Home" asp-action="PKCE">PKCE Flow</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li role="presentation"><a href="/userinformation">User Information</a></li>
                        <li role="presentation"><a asp-controller="Image" asp-action="Index">Images</a></li>
                        <li role="presentation"><a asp-controller="Home" asp-action="AssignRole">TestRoleAssignment</a></li>
                        <li role="presentation" class="active">
                            <form method="post" asp-controller="Auth" asp-action="SignOut">
                                <button type="submit" class="btn btn-primary">Sign Out</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li role="presentation" class="active"><a asp-controller="Auth" asp-action="SignIn">Sign In</a></li>
                    }
                </ul>
            </nav>
            <h3 class="text-muted">Demo</h3>
        </div>
        @RenderBody()
        <footer class="footer"></footer>
    </div>
</body>
</html>